global:
  scrape_interval: 5m
  evaluation_interval: 5m

scrape_configs:
  - job_name: 'shotgun-exporter'
    static_configs:
      - targets: ['shotgun-exporter:9090']
    scrape_interval: 5m
    scrape_timeout: 60s
